### ISSUE TITLE
Hellfire SPMA

### ISSUE THREAD

**Issue by HellDragon-HK** [GreatEmerald/UT3Vehicles#14]
Issues and notes on the Hellfire SPMA from in-game testing

UT2004 Draw  - 1.0
UT3    Draw  - 1.3
UT3Port Draw - 1.0 / 1.17, 1.20 gets it close to the right height but looks too long

  - [Priority]  
  - [Try 1.17 Drawscale or more because on UT3 the top of the front wheel and top of the back treads are above character head height, although if the wheels are separate this will need to be re-examined]  
  - [Port has no collision on main cannon]  
  - [Getting out of the SPMA on UT3 while it's deployed leaves the anchor arms in place and on the port they instantly just reset with no animation even]  
  - [Secondary]  
  - [On UT3 main cannon takes about 2 and half seconds to swing half way around, port feels like less than 1 second, also on UT3 doesn't have sound when turning but I prefer it having sound myself]  
  - [The camera shell is HUGE on UT2004 but on UT3 is actually fairly small by the look of it, on UT3 looks about the size of someone's head, on 2004 looks like the size of someone's chest....and I would also say the UT2004 one does a LOT more damage when it falls on your head (I went from 100 to 10 and on UT3 from 85 to 15)]  
  - [Port has headlights in correct place but generic and not team colored, also don't cast any light, stock UT2004 SPMA does with 4 beams of light]  
  - [Port is missing the lights just below the main cannon on the body]  
  - [Extra]  
  - [On UT3 SPMA is very slow like a UT2004 Paladin but the port is quite a bit faster]

**Comment by HellDragon-HK** [comment]
Impact tests for Hellfire SPMA which thanks to PS3 differences (or my game is just outright glitched) is less than complete

Hellfire SPMA Impact with Manta
-------UT3 Results--------
--Front Hit   - Little to no knockback (Hellfire doesn't have enough speed), easily pushed
--Side Hit    - No knockback, easily pushed
--Back Hit    - Little to no knockback, easily pushed
--Diagnol Hit - No knockback, easily pushed
------UT2004 Results------ 
--Front Hit   - Fair knockback, easily pushed
--Side Hit    - Fair knockback, easily pushed
--Back Hit    - Fair knockback, easily pushed
--Diagnol Hit - Fair knockback, easily pushed

Hellfire SPMA Impact with Scorpion
-------UT3 Results--------
--Front Hit   - No knockback, cannot be pushed but easily flips it over....darn not only did it flip it over it rolled on top of it and now it's stuck moving with the SPMA.....and now my SPMA is bottomed out with wheels completely off the ground wow
--Side Hit    - No knockback but Scopion flipped on it's side, SPMA rolls Scorpion over at slightest tap
--Back Hit    - No knockback and Scorpion is lifted off back wheels while SPMA is lifted off front wheels because it's lifting the Scorpion, push result is the same
--Diagnol Hit - SPMA incapable of knockback so from now on just push report which this was same as front
------UT2004 Results------ 
--Front Hit   - Little knockback and Scorpion is lifted off front wheels, cannot be pushed because SPMA drives over it also doesn't appear to be able to flip it
--Side Hit    - Little knockback and Scorpion flipped on it's side, pushing flips it
--Back Hit    - Little knockback and Scorpion was lifted off back wheels, can be pushed
--Diagnol Hit - Little knockback and both vehicles lifted off front wheels, either gets flipped or drove over but not pushed

Hellfire SPMA Impact with Hellbender
-------UT3 Results--------
--Front Hit   - Little knockback, trying to push lifts both vehicles off front wheels but can't really be pushed
--Side Hit    - No knockback and Hellbender is flipped with SPMA front wheels sitting on top of it, push gives same result
--Back Hit    - No knockback, pushing lifts Hellbender off back wheels and SPMA lifts off front wheels and Hellbender can be pushed like this
--Diagnol Hit - No knockback just pushed over
------UT2004 Results------ 
--Front Hit   - Little knockback, can be pushed
--Side Hit    - Little to no knockback, cannot be pushed or flipped which SPMA tries but doesn't succeed and falls back down
--Back Hit    - Little to no knockback, can be pushed
--Diagnol Hit - Little knockback, can be pushed

Hellfire SPMA Impact with Stealthbender
-------UT3 Results--------
--Front Hit   - unable to find map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Hellfire SPMA Impact with Raptor
-------UT3 Results--------
--Front Hit   - Little knockback, easily pushed
--Side Hit    - Little knockback, easily pushed
--Back Hit    - Little knockback, easily pushed
--Diagnol Hit - Little knockback, easily pushed and turned
------UT2004 Results------ 
--Front Hit   - Fair knockback, easily pushed like on ice
--Side Hit    - Little knockback, easily pushed like on ice
--Back Hit    - Fair knockback, easily pushed like on ice
--Diagnol Hit - Fair knockback and 90 degree spin, easily pushed and turned like on ice

Hellfire SPMA Impact with Cicada
-------UT3 Results--------
--Front Hit   - No knockback and Cicada front slightly lifted off ground, easily pushed
--Side Hit    - No knockback, easily pushed
--Back Hit    - No knockback, easily pushed
--Diagnol Hit - About the same as front hit
------UT2004 Results------ 
--Front Hit   - No knockback, can be pushed (not as easily as UT3)
--Side Hit    - Little knockback and 90 degreen spin, can be pushed
--Back Hit    - Little knockback, can be pushed
--Diagnol Hit - Little knockback and some spin, cannot be pushed but can be turned

Hellfire SPMA Impact with Hellfire SPMA
-------UT3 Results--------
--Front Hit   - No knockback and both lifted off front wheels, push result is the same
--Side Hit    - No knockback and other SPMA is nearly flipped, pushing is the same result
--Back Hit    - No knockback, other SPMA back lifted off ground and driving SPMA front lifted off ground, pushing is the same
--Diagnol Hit - Same as front result
------UT2004 Results------ 
--Front Hit   - Little knockback, can be slowly pushed
--Side Hit    - Little knockback, cannot be pushed or flipped
--Back Hit    - Little knockback, can be slowly pushed and other SPMA front wheel plating noticed to be turning with wheels
--Diagnol Hit - Little knockback, can be slowly pushed and turned

Hellfire SPMA Impact with Paladin
-------UT3 Results--------
--Front Hit   - can't find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - No knockback, can be slowly pushed
--Side Hit    - Little knockback and Paladin flipped on it's side, flips at slightest tap or more accurately tries to jump on top of SPMA
--Back Hit    - Little knockback and Paladin goes bottom up, lifts up on top of SPMA at slightest tap
--Diagnol Hit - Little knockback and Paladin goes vertical, lifts up on top of SPMA at slightest tap

Hellfire SPMA Impact with Goliath 
-------UT3 Results--------
--Front Hit   - unable to find map to test with (Hellfire missing on VCTF-Suspense and Goliath and SPMA nodes not active at same time for Torlan)
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - Very little knockback, can be slowly pushed
--Side Hit    - Very little knockback and some spin, can be slowly pushed
--Back Hit    - Very little knockback, can be slowly pushed
--Diagnol Hit - No knockback but did spin a little, cannot be pushed but can be turned

Hellfire SPMA Impact with Leviathan
-------UT3 Results--------
--Front Hit   - unable to find map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - Very little knockback, can be very slowly pushed
--Side Hit    - No knockback and Leviathan very slightly lifted off ground, cannot be pushed
--Back Hit    - Very little knockback, can be very slowly pushed
--Diagnol Hit - Very little knockback, can be very slowly pushed

Hellfire SPMA Impact with Viper
-------UT3 Results--------
--Front Hit   - unable to find a map that has both (SPMA not spawning in Torlan Necris)
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Hellfire SPMA Impact with Scavenger
-------UT3 Results--------
--Front Hit   - unable to find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Hellfire SPMA Impact with Nightshade
-------UT3 Results--------
--Front Hit   - unable to find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Hellfire SPMA Impact with Fury
-------UT3 Results--------
--Front Hit   - unable to find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending as well as pending being able to move the Fury where I need it as SPMA has turning issues currently and I won't be able to get the position needed
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 

Hellfire SPMA Impact with Nemesis
-------UT3 Results--------
--Front Hit   - unable to find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Hellfire SPMA Impact with Darkwalker
-------UT3 Results--------
--Front Hit   - unable to find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

**Comment by GreatEmerald** [comment]
Nice catch with the health, will fix.

Yes, the fenders of SPMA have the same issue as the Hellbender. They are attached to the wheel rather than the body (because in UT3 turning the wheel also turns the fender), but the UT2004 system controls the wheel spinning and anything attached to them. So I need to use a pretty ugly hack to reset the fender rotation on each tick and that can go awry easily.

The turning issues cannot be easily solved in UT2004 because it has no concept of a half-tread vehicle. Right now it's implemented as a wheeled vehicle.

I recall most of the physics issues from my testing as well. SPMA is kind of weird like that. Needs some experimentation with different physics options.

**Comment by GreatEmerald** [comment]
Fixed health amount in commit https://github.com/GreatEmerald/UT3Vehicles/commit/8cd2f2afb02694500af58f06c403a18e1894cab3.

**Comment by HellDragon-HK** [comment]
It's the front wheels that look like they have the issue, it's true with the Hellbender as well which doesn't have treads

**Comment by GreatEmerald** [comment]
Yes, that's the bone issue, as I mentioned. Ideally the fenders would not be attached to the wheels, but that requires editing the skeletal mesh...

**Comment by HellDragon-HK** [comment]
Ok I'm back, still don't understand this commit thing can you explain it also the Goliath is missing 100 points of health as well from what I saw I'll look at the uncode page and see if I can't confirm it for you

**Comment by GreatEmerald** [comment]
A commit is a change in code. I just made a change. If you go to your UT3Vehicles repository in Git Bash and run `git pull` you will receive this change.

**Comment by HellDragon-HK** [comment]
I lost the e-mail on how to do that, apparently they auto delete after awhile :(

**Comment by GreatEmerald** [comment]
Open Git Bash, enter `cd path/to/your/UT2004/UT3Vehicles`, enter `git pull`. Then recompile everything by removing `UT3Vehicles.u`, doing `cd path/to/your/UT2004/System` and running `ucc.exe make` in Command Prompt (or potentially Git Bash, I never tried that).

**Comment by HellDragon-HK** [comment]
Thanks I'll try to do that now

**Comment by GreatEmerald** [comment]
Oh right, you're on the wrong branch. Try `git checkout master` or `git checkout origin/master`, or just delete the UT3Vehicles directory altogether and do a new `git clone https://github.com/GreatEmerald/UT3Vehicles.git`.

**Comment by HellDragon-HK** [comment]
So then it did not download the update properly and I still need to do that?

**Comment by GreatEmerald** [comment]
Indeed.

**Comment by HellDragon-HK** [comment]
Darn ok then hang around please in case I can't get it to work as so far Git and I don't get along well.

**Comment by HellDragon-HK** [comment]
You said you can't see edits so here a post to get your attention if you don't mind, I tried running ucc make and I've got Can't find files matching UT3Vehicles\Classes\*.uc

**Comment by GreatEmerald** [comment]
You need to have the new UT3Vehicles folder. If you can see the new `Health` and `HealthMax` `defaultproperties` in `UT3HellfireSPMA`, then you got it, you just need to rerun `ucc make`.

**Comment by HellDragon-HK** [comment]
I don't have it and git clone didn't work so ?

**Comment by HellDragon-HK** [comment]
Trying to find the correct size here and a z scale of 1.2 looks right but causes it to float off the ground, changing the z translation to 45 fixes this and leaves the treads floating (which I noticed in UT3 on vehicle spawn the treads are indeed floating and are not once you drive the vehicle), however doing this causes a massive collision wall like with the Paladin and Goliath as well as the vehicle is unable to move and trying to deploy it's canon gives the wheels are unstable message.

**Comment by HellDragon-HK** [comment]
Hellfire SPMA sound update to include missing explosion and turret rotate (I tried to use Upload Files in the code area but I don't have permission)
https://drive.google.com/open?id=17UqS7l3-Jx-lbN34S0QrLVglb6WH2Gxh

Add to UT3HellfireSPMA
    DamagedEffectHealthSmokeFactor=0.65 //0.5
    DamagedEffectHealthFireFactor=0.37 //0.25
    DamagedEffectFireDamagePerSec=0.95 //0.75
    ImpactDamageSounds(0) = Sound'UT3A_Vehicle_Goliath.Sounds.A_Vehicle_Goliath_Collide01';
    ImpactDamageSounds(1) = Sound'UT3A_Vehicle_Goliath.Sounds.A_Vehicle_Goliath_Collide01';
    ImpactDamageSounds(2) = Sound'UT3A_Vehicle_Goliath.Sounds.A_Vehicle_Goliath_Collide01';
    ImpactDamageSounds(3) = Sound'UT3A_Vehicle_Goliath.Sounds.A_Vehicle_Goliath_Collide01';
    ImpactDamageSounds(4) = Sound'UT3A_Vehicle_Goliath.Sounds.A_Vehicle_Goliath_Collide01';
    ImpactDamageSounds(5) = Sound'UT3A_Vehicle_Goliath.Sounds.A_Vehicle_Goliath_Collide01';
    ImpactDamageSounds(6) = Sound'UT3A_Vehicle_Goliath.Sounds.A_Vehicle_Goliath_Collide01';
    ExplosionSounds(0) = Sound'UT3SPMA.A_Vehicle_SPMA_Explode01';
    ExplosionSounds(1) = Sound'UT3SPMA.A_Vehicle_SPMA_Explode01';
    ExplosionSounds(2) = Sound'UT3SPMA.A_Vehicle_SPMA_Explode01';
    ExplosionSounds(3) = Sound'UT3SPMA.A_Vehicle_SPMA_Explode01';
    ExplosionSounds(4) = Sound'UT3SPMA.A_Vehicle_SPMA_Explode01';

Add to UT3HellfireSPMASideGun
	bInstantRotation=false //(This is needed for the sound to work and it's fast but not instant in UT3 anyway)
	RotateSound=sound'UT3SPMA.A_Vehicle_SPMA_TurretRotate01'

Add to UT3HellfireSPMACannon
RotateSound=sound'UT3SPMA.SPMACannonRotate'

**Comment by GreatEmerald** [comment]
Hm, right, the coronas floating would not be great. You often see them while driving, too, so I think in this case it might be best to simply omit the coronas.

Yeah, I don't think you want to mess with vehicle factories... The level designers can choose whatever times they wish in a way that would meet their balance for the map. They can also choose to spawn a different vehicle, even if the name of it suggests a particular type of vehicle. I'm not even sure if they can be replaced. So don't worry about respawn times.

**Comment by HellDragon-HK** [comment]
Got a good surprise from the UT3 Drawscale, the SPMA is actually turning normally now, might still be too early to confirm it but why do you think that would be if it is truly fixed now?

**Comment by HellDragon-HK** [comment]
@Unre-Alex If you're trying the new drawscale I'm aware it's hard to get in the SPMA, the entry point for some odd reason seems to be above it near the cannon and middle of the vehicle

**Comment by GreatEmerald** [comment]
Hm, the only reason I could think of is that the wheel radius, which doesn't change when you just edit the binary, now matches the reality better.

**Comment by HellDragon-HK** [comment]
Whatever it is it did wonders, this thing handles completely normally now....would still like to hear from Alex and GP if they are getting the same result though

**Comment by GreatEmerald** [comment]
I made a separate issue for the fenders ("front plating"), you should remove them from the list and all the other lists of affected vehicles (Leviathan, Hellbender).

I see several more issues that are not specific to SPMA here. You can make separate issues (and remove from here and affected vehicles) for cannon collision (no vehicles have that) and death mesh (most are inaccurate).

Next, you should split off all issues that relate to the cannons to their own issues, because the cannons are a separate classes from the SPMA itself. Same with the projectiles, their issues should be in their own issues too because they have separate classes.

**Comment by HellDragon-HK** [comment]
Uhh that sound beyond confusing but ok I'll start doing that when I get through the rest of the e-mails here

**Comment by GreatEmerald** [comment]
OK, thanks, this is much easier to keep track of.

**Comment by HellDragon-HK** [comment]
Hellfire SPMA can not be used on network game by players, bots have no trouble, when a player (including host) gets in, the SPMA will not move, will not deploy, and if you fire it just keeps firing endlessly until you get out

**Comment by GreatEmerald** [comment]
Oh boy, replication issues, those are always fun... /s
